# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    container_name: postgres-d21
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin4-d21
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
volumes:
  data:
    external: true
